Repository ScratchAddons/website-v2, pull requests merged in 2022-03, with the labels that each got.

#159 Add blog section
  assets/assets/css/base.scss
  content/blog/_index.md
  content/blog/our-new-blog.md
  i18n/en.yaml
  layouts/_default/rss.xml
  layouts/blog/_markup/render-heading.html
  layouts/blog/baseof.html
  layouts/blog/section.html
  layouts/blog/single.html
  layouts/partials/footer.html
  layouts/partials/head.html
Labels: type: enhancement, scope: blog, scope: engine

#158 Minor i18n fixes
  i18n/en.yaml
  layouts/partials/nav.html
Labels: type: enhancement, scope: content

#156 Add addon count and link to source code
  assets/assets/css/base.scss
  i18n/en.yaml
  layouts/shortcodes/specifics/addons.html
Labels: type: enhancement, scope: content

#153 Add links to Edge Add-ons page
  content/docs/getting-started/installing.md
  content/docs/getting-started/quick-start.md
  i18n/en.yaml
  layouts/_default/home.html
  static/assets/js/website-base.js
Labels: type: enhancement, scope: content

#154 Remove links to griffpatch's website
  i18n/en.yaml
  layouts/_default/home.html
Labels: type: enhancement, scope: content

#155 Add admonition shortcode
  assets/assets/css/docs.scss
  assets/assets/css/parts/admonition.scss
  content/docs/localization/joining-the-localization-team.md
  layouts/shortcodes/admonition.html
Labels: type: enhancement, scope: engine

#151 Revamp credits page
  assets/assets/css/contributors.scss
  content/contributors.html
  content/credits.html
  data/credits/contributortypes/description/en.yml
  data/credits/contributortypes/symbol.yml
  data/credits/dependencies.yml
  i18n/en.yaml
  layouts/partials/footer.html
  layouts/partials/nav.html
  layouts/shortcodes/specifics/contributors.html
  layouts/shortcodes/specifics/dependencies.html
  static/assets/js/contributors.js
Labels: type: enhancement, scope: content

#160 [WIP] Change Firefox minimum supported version
  content/unsupported-browser.html
Labels: type: enhancement, scope: content

#165 Add link to privacy policy
  i18n/en.yaml
  layouts/partials/footer.html
Labels: type: enhancement, scope: content

#173 Add comments feature (Giscus)
  CODE_OF_CONDUCT.md
  content/docs/policies/code-of-conduct.md
  i18n/en.yaml
  layouts/blog/single.html
  layouts/docs/baseof.html
  layouts/partials/comments.html
  layouts/shortcodes/specifics/contributors.html
  static/assets/js/comments.js
  static/assets/js/website-base.js
Labels: type: enhancement, scope: engine

#174 Add missing period
  content/docs/localization/joining-the-localization-team.md
Labels: type: enhancement, scope: docs

#185 Improve feedback form
  i18n/en.yaml
  layouts/shortcodes/specifics/feedback-form.html
  static/assets/js/feedback.js
Labels: type: enhancement, scope: content
