Repository ScratchAddons/website-v2, pull requests merged in 2024-08, with the labels that each got.

#473 List more removed addon IDs
  content/docs/develop/getting-started/creating-an-addon.md
Labels: scope: docs

#453 Better Firefox installation instructions + Firefox for Android
  content/docs/getting-started/installing.md
Labels: scope: docs

#459 Add some new pages to addon docs
  content/addons/60fps.md
  content/addons/paint-by-default.md
Labels: type: enhancement, scope: docs

#483 Edit the `60fps` addon documentation
  content/addons/60fps.md
Labels: type: enhancement, scope: docs

#485 Fix .site.IsServer deprecation error
  .github/workflows/deploy-test.yml
  layouts/partials/docs/footer.html
Labels: type: bug, dependencies

#484 Add discuss-button page
  content/addons/discuss-button.md
  static/assets/img/addons/docs/compact-nav-dropdown.png
Labels: type: enhancement, scope: docs

#487 Add v1.39.0 to changelog
  data/changelog.yml
Labels: type: enhancement, scope: content

#454 Revert "Add Pre-send warning for 1.38.1 bug"
  i18n/en.yaml
  layouts/shortcodes/specifics/feedback-form.html
  static/assets/js/feedback.js
Labels: type: bug, scope: other

#490 Create blog post for release v1.39
  content/blog/v1-39-released.md
  static/assets/img/blog/v1-39-released/delete-others.mp4
  static/assets/img/blog/v1-39-released/import-and-replace.mp4
  static/assets/img/blog/v1-39-released/reply-chain.png
Labels: type: enhancement, scope: blog
